# Site settings
title: "Haris Zafeiropoulso and GeomScale @ GSoC2021"
description: "A blog for my project."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-target-blank


# Resume settings
resume_avatar:                  "true"
resume_name:                    "GSoC2021: extracting key metabolic processes"
resume_title:                   "About the project"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "haris.zafr@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "Twenty years after Covert W.Covert, Bernhard O. Palsson and their colleagues published their review on metabolic modelling of microbial strains, the value of this method has been well established. 
From the beginning, metabolic modeling has been interwoven with constraing-based methods. 
The value of randomized sampling in the framework of metabolic modeling has been proved itself over the years.
High Throughput Sequencing technologies have allowed process in the genetic information (DNA) in a cost-efficient and easy way, especially for microbial species as their genome is only but a few hundreds of genes long.
Once the complete genome of a species is obtained, the complete reconstruction of the metabolic network of the species is enabled, called genome-scale metabolic models (GEMs).
Such models for all the species present in a microbial community, allows the study 
of metabolic interactions, thus an insight for the actual microbial intaractions. 
Aim of this project is to integrate the produced data and knowledge of these twenty 
(and more) years and make use of the randomized flux sampling method 
to evaluate the metabolic interactions retrieved. 
To this end, thousands of publicly available reference microbial genomes will be 
selected, and their automatic metabolic network reconstructions will be implemented. 
Based on these models, cross-feeding interactions algorithms will be performed for groups
of species to extract key metabolic processes. 
New functions, implementing the recently developed Multiphase Monte Carlo Sampling (MMCS) approach in the framework  of the dingo library, will 
make use of the randomized flux sampling concept to evaluate the processes retrieved."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hariszaf/gsoc2021"
  resume_twitter_url:           "https://twitter.com/haris_zaf"
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/haris-zaf-44555711a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://hariszaf.github.io/"
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
